image: nixos/latest
repositories:
  nixpkgs: https://nixos.org/channels/nixos-19.09
sources:
  - https://git.sr.ht/~nloomans/noahloomans.com
environment:
  deploy: root@noahloomans.com
secrets:
  - a453c7e5-f773-4343-9fe3-ba3bf58492a3
tasks:
  - tutorial_makefile_repo: |
      mkdir -p noahloomans.com/src/tutorials
      git clone --bare https://git.sr.ht/~nloomans/noahloomans.com-tutorials-makefile noahloomans.com/src/tutorials/makefile
      git -C noahloomans.com/src/tutorials/makefile update-server-info
  - build: |
      cd noahloomans.com
      nix-build
  - deploy: |
      cd noahloomans.com
      # We only want to deploy when on master. We cain't just check if
      # --abbrev-ref is master since the HEAD is detached.
      if [ "$(git rev-parse master)" = "$(git rev-parse HEAD)" ]; then
        rsync \
          --rsh='ssh -o StrictHostKeyChecking=no' \
          --delete \
          --recursive \
          --progress \
          result/www/. $deploy:/var/www/noahloomans.com/html/
      else
        echo "Not on master, skipping..."
        find result/www
      fi
