include: [".well-known"]
markdown: kramdown
sass:
    sass_dir: style

email: inbox@noahloomans.com
email_markdown: "[inbox@noahloomans.com](mailto:inbox@noahloomans.com)"

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      permalink: /:categories/:title/
